- name: Get Grafana ServiceAccount Token
  k8s_info:
    kind: Secret
    name:  '{{ item.name }}'
    namespace: '{{ cluster_project }}'
    api_version: v1
  register: r_grafana_secret
  until:
    - r_grafana_secret.resources is defined
  retries: 10
  delay: 15

- name: Set grafana_token
  set_fact:
    grafana_token: '{{ r_grafana_secret.resources[0].data.token | b64decode }}'
  when:
    - r_grafana_secret.resources[0].data.token is defined
